In [11]:
import numpy as np

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
type(np.zeros((3,4)))

numpy.ndarray

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [18]:
np.empty((2,3))

array([[5.29895456e-310, 0.00000000e+000, 1.69430015e-152],
       [5.30992040e+180, 7.23011111e+165, 1.23973013e+224]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [23]:
print(np.arange(0, 5/3, 1/3)) # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))


[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333334]


In [25]:
""""
However, when dealing with floats, the exact number of elements in the array is not always predictable. 
For this reason, it is generally preferable to use the linspace function instead of arange when working with floats. 
The linspace function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is included, contrary to arange):
"""
print(np.linspace(0, 5/3, 6))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [26]:
np.random.rand(3,4)

array([[0.56696242, 0.98728969, 0.13185938, 0.54497116],
       [0.73792369, 0.37833364, 0.27087299, 0.07908233],
       [0.70760234, 0.74620765, 0.18867342, 0.4773195 ]])

In [27]:
np.random.randn(3,4)

array([[ 0.41595164, -1.54287262, -1.85459506,  0.18240068],
       [-0.11149378,  0.58132591, -0.10731315, -0.46503192],
       [-0.1935743 , -0.28805388, -1.45344201, -1.06794982]])

In [29]:
c = np.arange(1.0, 5.0)
print(c.dtype, c, c.itemsize)

float64 [1. 2. 3. 4.] 8


In [31]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [32]:
g.shape = (6, 4)
print(g)
print("Rank:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rank: 2


In [33]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


In [34]:
g2 = g.reshape(4,6)
print('g: ', g)
print('Rank of g:', g.ndim)
print('g2: ', g2)
print("Rank of g2:", g2.ndim)

g:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank of g: 3
g2:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Rank of g2: 2


In [35]:
g.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

a + b  = [19 27 35 43]
a - b  = [ 9 19 29 39]
a * b  = [70 92 96 82]
a / b  = [ 2.8         5.75       10.66666667 20.5       ]
a // b  = [ 2  5 10 20]
a % b  = [4 3 2 1]
a ** b = [537824 279841  32768   1681]


In [37]:
""""
NumPy Array Broadcasting
Broadcasting is a mechanism in NumPy that allows performing element-wise operations on arrays with different shapes. The following rules govern broadcasting:

Arrays with different numbers of dimensions: If the arrays have different numbers of dimensions, the array with fewer dimensions can have its shape prepended with ones.
Example: np.array([1, 2, 3]) (1D) can be broadcasted to np.array([[1], [2], [3]]) (2D) by adding ones to the leading dimension.

Matching dimensions: If the arrays have the same number of dimensions, the lengths of each dimension must either be equal or one of them must be 1.
Example: np.array([[1, 2], [3, 4]]) (2D) can be broadcasted to np.array([[1], [2], [3], [4]]) (2D) by stretching the shorter array to match the longer one.

Error on mismatch: If the arrays have different lengths in any dimension and neither is 1, a ValueError is raised.
Example: np.array([[1, 2], [3, 4]]) (2D) cannot be broadcasted to np.array([[1, 2], [3]]) (2D) because the lengths of the second dimension do not match.

Examples
Scalar + Array: A scalar can be broadcasted to an array by duplicating its value along the leading dimensions.
Example: np.array([1, 2, 3]) + 4 → [5, 6, 7]

Array + Array: Two arrays with compatible shapes can be broadcasted and added element-wise.
Example: np.array([[1, 2], [3, 4]]) + np.array([[5, 6], [7, 8]]) → [[6, 8], [10, 12]]

Array + Scalar: An array can be broadcasted to a scalar by duplicating its shape and value.
Example: np.array([[1, 2], [3, 4]]) + 2 → [[3, 4], [5, 6]]

"""

'"\nNumPy Array Broadcasting\nBroadcasting is a mechanism in NumPy that allows performing element-wise operations on arrays with different shapes. The following rules govern broadcasting:\n\nArrays with different numbers of dimensions: If the arrays have different numbers of dimensions, the array with fewer dimensions can have its shape prepended with ones.\nExample: np.array([1, 2, 3]) (1D) can be broadcasted to np.array([[1], [2], [3]]) (2D) by adding ones to the leading dimension.\n\nMatching dimensions: If the arrays have the same number of dimensions, the lengths of each dimension must either be equal or one of them must be 1.\nExample: np.array([[1, 2], [3, 4]]) (2D) can be broadcasted to np.array([[1], [2], [3], [4]]) (2D) by stretching the shorter array to match the longer one.\n\nError on mismatch: If the arrays have different lengths in any dimension and neither is 1, a ValueError is raised.\nExample: np.array([[1, 2], [3, 4]]) (2D) cannot be broadcasted to np.array([[1, 2], 

In [47]:
h = np.arange(5)
h = np.arange(5).reshape(1, 5)
h = np.arange(5).reshape(1,1,5)
print(h, h.shape)

[[[0 1 2 3 4]]] (1, 1, 5)


In [51]:
# here, 1 is prepended to the shape of the array with fewer dimensions i.e, [10,20,30,40,50] so that it becomes [1,1,5]
h + [10, 20, 30, 40, 50]
print(np.array([10, 20, 30, 40, 50]).shape)
print(h.shape)

(5,)
(1, 1, 5)


In [52]:
k = np.arange(6).reshape(2, 3)
k

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
"""Arrays with a 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension.
 The value of the array element is repeated along that dimension"""

'Arrays with a 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension.\n The value of the array element is repeated along that dimension'

In [53]:
k + [[100], [200]]  # same as: k + [[100, 100, 100], [200, 200, 200]]

array([[100, 101, 102],
       [203, 204, 205]])

In [56]:
k + [100, 200, 300]  # after rule 1: [[100, 200, 300]], and after rule 2: [[100, 200, 300], [100, 200, 300]]

array([[100, 201, 302],
       [103, 204, 305]])

In [57]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [58]:
m[m < 25]

array([20, -5])

In [59]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
mean = 6.766666666666667


In [68]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
  print(func.__name__, "=", func())

min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.084835843520964
var = 25.855555555555554


In [63]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [66]:
c.sum(axis = 0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [67]:
c.sum(axis = 1)  # sum across rows

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [71]:
c.sum(axis = 2)  # sum across columns

array([[ 6, 22, 38],
       [54, 70, 86]])

In [70]:
c.sum(axis = (0,2))  # sum across matrices and columns

array([ 60,  92, 124])

In [72]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

array([[  6.25,   9.61,  49.  ],
       [100.  , 121.  , 144.  ]])

In [74]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
  print("\n", func.__name__)
  print(func(a))

Original ndarray
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


/tmp/ipykernel_16976/1617351232.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(func(a))
/tmp/ipykernel_16976/1617351232.py:5: RuntimeWarning: invalid value encountered in log
  print(func(a))


In [78]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[2:5] = -1
a

array([ 1,  2, -1, -1, -1,  6,  7,  8,  9])

In [79]:
a_slice = a[2:6]
a_slice[1] = 1000
a  # the original array was modified!

array([   1,    2,   -1, 1000,   -1,    6,    7,    8,    9])

In [80]:
a[3] = 2000
a_slice  # similarly, modifying the original array modifies the slice!

array([  -1, 2000,   -1,    6])

In [81]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a  # the original array is untouched

array([   1,    2,   -1, 2000,   -1,    6,    7,    8,    9])

In [82]:
a[3] = 4000
another_slice  # similarly, modifying the original array does not affect the slice copy

array([  -1, 3000,   -1,    6])

In [83]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [84]:
b[1, 2]  # row 1, col 2

np.int64(14)

In [85]:
b[1, :]  # row 1, all columns

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [86]:
b[:, 1]  # all rows, column 1

array([ 1, 13, 25, 37])

In [88]:
q1 = np.full((3,4), 1.7)
q1

array([[1.7, 1.7, 1.7, 1.7],
       [1.7, 1.7, 1.7, 1.7],
       [1.7, 1.7, 1.7, 1.7]])